Predict error file = D:\Dataset_and_Demo\2022-11-28_to_2023-02-25\01589_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2021-09-15_to_2021-11-28\03275_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2021-09-15_to_2021-11-28\03280_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2022-11-28_to_2023-02-25\01626_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2021-09-15_to_2021-11-28\03341_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2021-09-15_to_2021-11-28\03383_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2021-09-15_to_2021-11-28\04560_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2022-11-28_to_2023-02-25\02822_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2023-11-28_to_2024-02-25\00471_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2023-11-28_to_2024-02-25\01305_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2023-11-28_to_2024-02-25\02107_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2023-11-28_to_2024-02-25\02132_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2023-11-28_to_2024-02-25\02243_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2023-11-28_to_2024-02-25\02262_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2023-11-28_to_2024-02-25\02663_ADMeanFused_WithTiles_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2023-11-28_to_2024-02-25\02678_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2023-11-28_to_2024-02-25\02815_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2023-11-28_to_2024-02-25\04345_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2023-11-28_to_2024-02-25\04356_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00025_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00037_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00040_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00042_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00046_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00059_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00136_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00146_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00153_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00166_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00271_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00282_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00840_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00841_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\00870_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\01018_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\01466_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\01597_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\02202_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\02458_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\02981_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\03570_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\03614_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\03725_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\03816_ADMeanFused_WithTiles_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\03899_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04068_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04082_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04096_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04242_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04268_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04315_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04336_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04362_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04392_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04409_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04516_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04547_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04623_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04656_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04670_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04703_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04704_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04712_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04731_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04763_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04767_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04768_ADMeanFused_WithTiles_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04775_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04780_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04785_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Predict error file = D:\Dataset_and_Demo\2024-05-31_to_2024-09-15\04875_ADMeanFused_Trans.tif
Traceback (most recent call last):
  File "d:\09_Code\Gis_Script\05_SAM\º‡Ã˝SAM.py", line 51, in process_file
    AOI_Bound_Info = json.load(f)
                     ^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Wrz\anaconda\envs\GEE\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

